package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	domain "github.com/Omar-Sa6ry/realtime-bidding-microservices/services/bidding-service/internal/domains"
)

// FindBidByID is the resolver for the findBidByID field.
func (r *entityResolver) FindBidByID(ctx context.Context, id string) (*domain.Bid, error) {
	panic(fmt.Errorf("not implemented: FindBidByID - findBidByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
