package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"time"

	"github.com/Omar-Sa6ry/realtime-bidding-microservices/services/bidding-service/graph/model"
	domains "github.com/Omar-Sa6ry/realtime-bidding-microservices/services/bidding-service/internal/domains"
	middlewares "github.com/Omar-Sa6ry/realtime-bidding-microservices/services/bidding-service/internal/middlewares"
)

// Status is the resolver for the status field.
func (r *bidResolver) Status(ctx context.Context, obj *domains.Bid) (string, error) {
	return string(obj.Status), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *bidResolver) CreatedAt(ctx context.Context, obj *domains.Bid) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// PlaceBid is the resolver for the placeBid field.
func (r *mutationResolver) PlaceBid(ctx context.Context, auctionID string, amount float64) (*model.BidResponse, error) {
	userID := middlewares.GetUserIDFromContext(ctx)

	bid, err := r.BiddingService.PlaceBid(ctx, auctionID, userID, amount)
	if err != nil {
		return &model.BidResponse{
			Success:    false,
			Message:    err.Error(),
			StatusCode: 400,
			TimeStamp:  time.Now().Format("2006-01-02T15:04:05Z07:00"),
		}, nil
	}

	return &model.BidResponse{
		Success:    true,
		Message:    "Bid placed successfully",
		StatusCode: 201,
		TimeStamp:  time.Now().Format("2006-01-02T15:04:05Z07:00"),
		Data:       bid,
	}, nil
}

// GetAuctionHistory is the resolver for the getAuctionHistory field.
func (r *queryResolver) GetAuctionHistory(ctx context.Context, auctionID string) ([]*domains.Bid, error) {
	return r.BiddingService.GetAuctionHistory(ctx, auctionID)
}

// Bid returns BidResolver implementation.
func (r *Resolver) Bid() BidResolver { return &bidResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type bidResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
