apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: realtime-bidding-microservices

build:
  local:
    push: false
  artifacts:
    - image: bidding/user
      context: services/user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

manifests:
  rawYaml:
    - k8s/*.yaml
