apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: realtime-bidding-microservices

build:
  local:
    push: false

manifests:
  rawYaml:
    - k8s/*.yaml



# docker build -t bidding/ooooooooooo:latest .
# docker pull node:24.11.0

# minikube start --driver=docker --image-mirror-country=all --base-image=docker.io/kicbase/stable:v0.0.48

# minikube status
# minikube addons enable ingress
# kubectl apply -f k8s
# & minikube -p minikube docker-env | Invoke-Expression

# skaffold dev --cache-artifacts=true

# minikube tunnel
