// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	domain "github.com/Omar-Sa6ry/realtime-bidding-microservices/services/bidding-service/internal/domains"
)

type Auction struct {
	ID string `json:"id"`
}

func (Auction) IsEntity() {}

type BidResponse struct {
	Success    bool        `json:"success"`
	Message    string      `json:"message"`
	StatusCode int         `json:"statusCode"`
	TimeStamp  string      `json:"timeStamp"`
	Data       *domain.Bid `json:"data,omitempty"`
}

type BidsResponse struct {
	Success     bool          `json:"success"`
	Message     string        `json:"message"`
	StatusCode  int           `json:"statusCode"`
	TimeStamp   string        `json:"timeStamp"`
	Data        []*domain.Bid `json:"data,omitempty"`
	TotalPages  *int          `json:"totalPages,omitempty"`
	CurrentPage *int          `json:"currentPage,omitempty"`
	TotalItems  *int          `json:"totalItems,omitempty"`
}

type Mutation struct {
}

type PaginationInput struct {
	Limit *int `json:"limit,omitempty"`
	Page  *int `json:"page,omitempty"`
}

type Query struct {
}
