// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	domain "github.com/Omar-Sa6ry/realtime-bidding-microservices/services/bidding-service/internal/domains"
)

type BidResponse struct {
	Success    bool        `json:"success"`
	Message    string      `json:"message"`
	StatusCode int         `json:"statusCode"`
	TimeStamp  string      `json:"timeStamp"`
	Data       *domain.Bid `json:"data,omitempty"`
}

type BidsResponse struct {
	Success    bool          `json:"success"`
	Message    string        `json:"message"`
	StatusCode int           `json:"statusCode"`
	TimeStamp  string        `json:"timeStamp"`
	Data       []*domain.Bid `json:"data,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
