apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-db
  template:
    metadata:
      labels:
        app: auction-db
    spec:
      containers:
        - name: auction-db
          image: mongo:6.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auction-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auction-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: bidding-auction_service_dev
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: auction-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auction-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: auction-db-srv
spec:
  selector:
    app: auction-db
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
