apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bidding.test
      secretName: bidding-tls
  rules:
    - host: bidding.test
      http:
        paths:
          # gateway-service routes
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: api-gateway-srv
                port:
                  number: 4000