apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bidding.test
      secretName: bidding-tls
  rules:
    - host: bidding.test
      http:
        paths:
          # gateway-service routes
          - path: /()(graphql.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-gateway-srv
                port:
                  number: 4000