apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: bidding/notification
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT_NOTIFICATION
              value: "3004"
            - name: NATS_URL
              value: "nats://nats-srv:4222"
            - name: JWT_EXPIRE
              value: "36000s"
            - name: REDIS_HOST
              value: "redis-srv"
            - name: REDIS_PORT
              value: "6379"
            - name: USER_SERVICE_URL
              value: "user-srv:50051"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: notification-secrets
                  key: JWT_SECRET
          envFrom:
            - secretRef:
                name: notification-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: notification-srv
spec:
  selector:
    app: notification
  ports:
    - name: http
      protocol: TCP
      port: 3004
      targetPort: 3004
