apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: bidding/user 
          ports:
            - containerPort: 3000 
            - containerPort: 50051
          env:
            - name: PORT_USER
              value: '3000'
            - name: DB_HOST
              value: 'user-db-srv'
            - name: DB_PORT
              value: '5432'
            - name: DB_NAME
              value: 'bidding_user_db'
            - name: NODE_ENV
              value: 'development'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRE
              value: '36000s'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: POSTGRES_PASSWORD
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: STRIPE_WEBHOOK_SECRETSUCCESSURL
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: STRIPE_WEBHOOK_SECRETSUCCESSURL
            - name: STRIPE_WEBHOOK_SECRETFAILURL
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: STRIPE_WEBHOOK_SECRETFAILURL
            - name: REDIS_HOST
              value: 'redis-srv'
            - name: REDIS_PORT
              value: '6379'
            - name: NATS_URL
              value: 'nats://nats-srv:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
