package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/Omar-Sa6ry/realtime-bidding-microservices/services/auction-service/graph/model"
)

// FindAuctionByID is the resolver for the findAuctionByID field.
func (r *entityResolver) FindAuctionByID(ctx context.Context, id string) (*model.Auction, error) {
	auction, err := r.AuctionService.FindByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if auction == nil {
		return nil, nil
	}
	return mapDomainToModel(auction), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
