package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"time"

	"github.com/Omar-Sa6ry/realtime-bidding-microservices/services/auction-service/graph/model"
	service "github.com/Omar-Sa6ry/realtime-bidding-microservices/services/auction-service/internal/services"
)

// CreateAuction is the resolver for the createAuction field.
func (r *mutationResolver) CreateAuction(ctx context.Context, input model.CreateAuctionInput) (*model.AuctionResponse, error) {
	auction, err := r.AuctionService.CreateAuction(ctx, service.CreateAuctionParams{
		Title:         input.Title,
		Description:   input.Description,
		StartingPrice: input.StartingPrice,
		Currency:      input.Currency,
		StartTime:     input.StartTime,
		EndTime:       input.EndTime,
		Images:        input.Images,
	})
	if err != nil {
		return nil, err
	}

	return &model.AuctionResponse{
		Success:    true,
		Message:    "Auction created successfully",
		StatusCode: 201,
		TimeStamp:  time.Now().Format(time.RFC3339),
		Data:       mapDomainToModel(auction),
	}, nil
}

// Auctions is the resolver for the auctions field.
func (r *queryResolver) Auctions(ctx context.Context) ([]*model.Auction, error) {
	return []*model.Auction{}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
