// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/Omar-Sa6ry/realtime-bidding-microservices/services/auction-service/internal/domain"
)

type Auction struct {
	ID            string               `json:"id"`
	Title         string               `json:"title"`
	Description   string               `json:"description"`
	StartingPrice float64              `json:"startingPrice"`
	CurrentPrice  float64              `json:"currentPrice"`
	Currency      string               `json:"currency"`
	Images        []string             `json:"images"`
	Status        domain.AuctionStatus `json:"status"`
	StartTime     string               `json:"startTime"`
	EndTime       string               `json:"endTime"`
	SellerID      string               `json:"sellerId"`
	WinnerID      *string              `json:"winnerId,omitempty"`
	CreatedAt     string               `json:"createdAt"`
	UpdatedAt     string               `json:"updatedAt"`
}

func (Auction) IsEntity() {}

type CreateAuctionInput struct {
	Title         string  `json:"title"`
	Description   string  `json:"description"`
	StartingPrice float64 `json:"startingPrice"`
	Currency      string  `json:"currency"`
	StartTime     string  `json:"startTime"`
	EndTime       string  `json:"endTime"`
}

type Mutation struct {
}

type Query struct {
}
