// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

type Auction struct {
	ID            string        `json:"id"`
	Title         string        `json:"title"`
	Description   string        `json:"description"`
	StartingPrice float64       `json:"startingPrice"`
	CurrentPrice  float64       `json:"currentPrice"`
	Currency      string        `json:"currency"`
	Images        []string      `json:"images"`
	Status        AuctionStatus `json:"status"`
	StartTime     string        `json:"startTime"`
	EndTime       string        `json:"endTime"`
	SellerID      string        `json:"sellerId"`
	Seller        *User         `json:"seller"`
	WinnerID      *string       `json:"winnerId,omitempty"`
	CreatedAt     string        `json:"createdAt"`
	UpdatedAt     string        `json:"updatedAt"`
}

func (Auction) IsEntity() {}

type AuctionResponse struct {
	Success    bool     `json:"success"`
	Message    string   `json:"message"`
	StatusCode int32    `json:"statusCode"`
	TimeStamp  string   `json:"timeStamp"`
	Data       *Auction `json:"data,omitempty"`
}

type AuctionsResponse struct {
	Success     bool       `json:"success"`
	Message     string     `json:"message"`
	StatusCode  int32      `json:"statusCode"`
	TimeStamp   string     `json:"timeStamp"`
	Data        []*Auction `json:"data"`
	TotalPages  *int32     `json:"totalPages,omitempty"`
	CurrentPage *int32     `json:"currentPage,omitempty"`
	TotalItems  *int32     `json:"totalItems,omitempty"`
}

type CreateAuctionInput struct {
	Title         string            `json:"title"`
	Description   string            `json:"description"`
	StartingPrice float64           `json:"startingPrice"`
	Currency      string            `json:"currency"`
	StartTime     string            `json:"startTime"`
	EndTime       string            `json:"endTime"`
	Images        []*graphql.Upload `json:"images,omitempty"`
}

type FindAuctionsInput struct {
	Title       *string        `json:"title,omitempty"`
	Description *string        `json:"description,omitempty"`
	Status      *AuctionStatus `json:"status,omitempty"`
	StartTime   *string        `json:"startTime,omitempty"`
	EndTime     *string        `json:"endTime,omitempty"`
	Currency    *string        `json:"currency,omitempty"`
}

type Mutation struct {
}

type PaginationInput struct {
	Limit *int32 `json:"limit,omitempty"`
	Page  *int32 `json:"page,omitempty"`
}

type Query struct {
}

type UpdateAuctionInput struct {
	Title         *string           `json:"title,omitempty"`
	Description   *string           `json:"description,omitempty"`
	Status        *AuctionStatus    `json:"status,omitempty"`
	StartTime     *string           `json:"startTime,omitempty"`
	EndTime       *string           `json:"endTime,omitempty"`
	Currency      *string           `json:"currency,omitempty"`
	StartingPrice *float64          `json:"startingPrice,omitempty"`
	Images        []*graphql.Upload `json:"images,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	Firstname *string `json:"firstname,omitempty"`
	Lastname  *string `json:"lastname,omitempty"`
}

func (User) IsEntity() {}

type AuctionStatus string

const (
	AuctionStatusPending   AuctionStatus = "PENDING"
	AuctionStatusActive    AuctionStatus = "ACTIVE"
	AuctionStatusEnded     AuctionStatus = "ENDED"
	AuctionStatusCancelled AuctionStatus = "CANCELLED"
)

var AllAuctionStatus = []AuctionStatus{
	AuctionStatusPending,
	AuctionStatusActive,
	AuctionStatusEnded,
	AuctionStatusCancelled,
}

func (e AuctionStatus) IsValid() bool {
	switch e {
	case AuctionStatusPending, AuctionStatusActive, AuctionStatusEnded, AuctionStatusCancelled:
		return true
	}
	return false
}

func (e AuctionStatus) String() string {
	return string(e)
}

func (e *AuctionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuctionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuctionStatus", str)
	}
	return nil
}

func (e AuctionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuctionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuctionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Permission string

const (
	PermissionUpdateUser         Permission = "UPDATE_USER"
	PermissionDeleteUser         Permission = "DELETE_USER"
	PermissionEditUserRole       Permission = "EDIT_USER_ROLE"
	PermissionViewUser           Permission = "VIEW_USER"
	PermissionCreateInstructor   Permission = "CREATE_INSTRUCTOR"
	PermissionResetPassword      Permission = "RESET_PASSWORD"
	PermissionChangePassword     Permission = "CHANGE_PASSWORD"
	PermissionForgotPassword     Permission = "FORGOT_PASSWORD"
	PermissionRechargeWallet     Permission = "RECHARGE_WALLET"
	PermissionLogout             Permission = "LOGOUT"
	PermissionCreateNotification Permission = "CREATE_NOTIFICATION"
	PermissionReadNotification   Permission = "READ_NOTIFICATION"
	PermissionUpdateNotification Permission = "UPDATE_NOTIFICATION"
	PermissionDeleteNotification Permission = "DELETE_NOTIFICATION"
	PermissionCreateAuction      Permission = "CREATE_AUCTION"
	PermissionUpdateAuction      Permission = "UPDATE_AUCTION"
	PermissionDeleteAuction      Permission = "DELETE_AUCTION"
	PermissionCreateBid          Permission = "CREATE_BID"
)

var AllPermission = []Permission{
	PermissionUpdateUser,
	PermissionDeleteUser,
	PermissionEditUserRole,
	PermissionViewUser,
	PermissionCreateInstructor,
	PermissionResetPassword,
	PermissionChangePassword,
	PermissionForgotPassword,
	PermissionRechargeWallet,
	PermissionLogout,
	PermissionCreateNotification,
	PermissionReadNotification,
	PermissionUpdateNotification,
	PermissionDeleteNotification,
	PermissionCreateAuction,
	PermissionUpdateAuction,
	PermissionDeleteAuction,
	PermissionCreateBid,
}

func (e Permission) IsValid() bool {
	switch e {
	case PermissionUpdateUser, PermissionDeleteUser, PermissionEditUserRole, PermissionViewUser, PermissionCreateInstructor, PermissionResetPassword, PermissionChangePassword, PermissionForgotPassword, PermissionRechargeWallet, PermissionLogout, PermissionCreateNotification, PermissionReadNotification, PermissionUpdateNotification, PermissionDeleteNotification, PermissionCreateAuction, PermissionUpdateAuction, PermissionDeleteAuction, PermissionCreateBid:
		return true
	}
	return false
}

func (e Permission) String() string {
	return string(e)
}

func (e *Permission) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Permission(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Permission", str)
	}
	return nil
}

func (e Permission) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Permission) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Permission) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
